chore: library upgrade
SwissDataScienceCenter/renkulab-docker pull request #251
Opened 2022-07-22 10:42 UTC by rokroskar

upgrades the libraries pinned in the base image.

2022-07-22 15:14 UTC, rokroskar commented
@olevski @gavin-k-lee a bunch of things are changed here in these images so it would be great if you could give them a once-over. They seem fine to me. Note also that since the default python version in the latest `jupyter/base-notebook`images is 3.10, we now inherit this python version as well. We'll need to update the templates and probably announce it to the users in the release notes.

2022-07-25 15:38 UTC, lorenzo-cavazzi commented on docker/py/Dockerfile
> +ARG RENKU_VERSION=1.5.0
```suggestion
ARG RENKU_VERSION=1.6.0
```

2022-07-26 07:47 UTC, Panaetius commented
According to https://docs.python.org/3/whatsnew/3.9.html#you-should-check-for-deprecationwarning-in-your-code 3.9 is the last version to contain 2.7 backwards compatibility layer and https://docs.python.org/3/whatsnew/3.10.html#removed did in fact remove some module methods and quite a lot of C API functions/types (at the end of the page). So 3.10 probably has a bit higher chance of breaking things than was the case with 3.9

We do NOT have tests for 3.10 in renku-python, so upgrading to 3.10 would essentially be flying blind, plus the higher risk of breaking user code does mean it'd make sense to upgrade to a version prior to https://github.com/jupyter/docker-stacks/blame/0be9e335026b21a452c888481ab6341dcdd183a5/base-notebook/Dockerfile#L88

2022-07-26 09:10 UTC, rokroskar commented
Something is wrong with the `cuda-tf` builds - also failing on master. Will make an issue to fix it.

2022-07-27 13:07 UTC, olevski commented on docker/py/Dockerfile
> +    git-lfs=3.1.4 \
Why not leave this at 3.2.0?

2022-07-27 13:11 UTC, olevski submitted a review, later dismissed

2022-07-27 15:00 UTC, olevski approved these changes

2022-07-27 15:09 UTC, merged

2022-07-27 15:13 UTC, olevski requested changes

2022-07-27 15:13 UTC, olevski commented on .github/workflows/build_and_push_to_docker.yml
> +          export LABEL_PREFIX=3.10
@rokroskar I thought none of the images are using python 3.10. And from Ralf's comment it seems we are not ready for 3.10 yet.

So this should then probably be rolled back to 3.9?

2022-07-27 15:13 UTC, olevski commented on .github/workflows/build_and_push_to_docker.yml
> +          --build-arg BASE_IMAGE="$DOCKER_NAME-py:3.10-$LABEL" \
```suggestion
          --build-arg BASE_IMAGE="$DOCKER_NAME-py:3.9-$LABEL" \
```

2022-07-27 15:13 UTC, olevski commented on .github/workflows/build_and_push_to_docker.yml
> +          --build-arg RENKU_BASE="$DOCKER_NAME-py:3.10-$LABEL" \
```suggestion
          --build-arg RENKU_BASE="$DOCKER_NAME-py:3.9-$LABEL" \
```

2022-07-27 15:13 UTC, olevski commented on .github/workflows/build_and_push_to_docker.yml
> +          --build-arg RENKU_BASE="$DOCKER_NAME-py:3.10-$LABEL" \
```suggestion
          --build-arg RENKU_BASE="$DOCKER_NAME-py:3.9-$LABEL" \
```

2022-07-27 15:13 UTC, olevski commented on .github/workflows/build_and_push_to_docker.yml
> +          --build-arg RENKU_BASE="$DOCKER_NAME-py:3.10-$LABEL" \
```suggestion
          --build-arg RENKU_BASE="$DOCKER_NAME-py:3.9-$LABEL" \
```

2022-07-27 15:13 UTC, olevski commented on .github/workflows/build_and_push_to_docker.yml
> +          --build-arg BASE_IMAGE="python:3.10-slim-buster" \
```suggestion
          --build-arg BASE_IMAGE="python:3.9-slim-buster" \
```

2022-07-27 15:13 UTC, olevski commented on .github/workflows/build_and_push_to_docker.yml
> +          --build-arg BASE_IMAGE="$DOCKER_NAME-py:3.10-$LABEL" \
```suggestion
          --build-arg BASE_IMAGE="$DOCKER_NAME-py:3.9-$LABEL" \
```

2022-07-27 15:13 UTC, olevski commented on .github/workflows/build_and_push_to_docker.yml
> +          export LABEL_PREFIX=3.10
```suggestion
          export LABEL_PREFIX=3.9
```